# Generated by Django 5.2.1 on 2025-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('was_executed_before', models.BooleanField(default=False)),
                ('log', models.TextField()),
            ],
        ),
    ]
