# Generated by Django 5.2.1 on 2025-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_cli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='code',
            field=models.TextField(verbose_name='Введите команду ssh'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='log',
            field=models.TextField(default='None', verbose_name='Результат выполнения'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='was_executed_before',
            field=models.BooleanField(default=False, verbose_name='Уже выполнялась'),
        ),
    ]
