# Generated by Django 5.2.1 on 2025-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_cli', '0004_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField(verbose_name='test')),
                ('another_field', models.CharField(verbose_name='field')),
            ],
        ),
    ]
