# Generated by Django 5.2.1 on 2025-08-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_cli', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
