# Generated by Django 5.2.1 on 2025-09-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_cli', '0011_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
